### ISSUE TITLE
登出键不可用

### ISSUE THREAD

**Issue by Tansc161** [cs12341795/yuribot#1]
点了登出键后有发出请求但没登出。

## 调试信息：
请求返回的数据
```HTTP
HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
Content-Type: text/plain; charset=utf-8
Content-Length: 3
Set-Cookie: （用户资料）
Date: （执行时间）
Via: 1.1 vegur

bye
```

**Comment by ArmFire1911** [comment]
在這個畫面按下登出後
https://imgur.com/QPueowF.png
會進入授權畫面
https://i.imgur.com/PJQcKTd.png

如果這是登出的話那應該是正常的
以上

**Comment by rueian** [comment]
登出請求返回的 Set-Cookie 裡面其實已經沒有資料了

還是你們覺得用加上 expires 或 max-age 的方式比較好？

**Comment by Tansc161** [comment]
如果用前端清除cookie的方法呢？
我开了个PR，在我自己的虚拟机测试是没问题，你们稍微检查下再看要不要Merge吧
https://github.com/cs12341795/yuribot/pull/5

**Comment by rueian** [comment]
你是用什麼瀏覽器啊？

**Comment by Tansc161** [comment]
我在删除键那个issue有写到吧

**Google Chrome |** 67.0.3396.87 (正式版本) （64 位） (cohort: Stable)
**修订版本 |** 878cd31214ac27a3996927cd5c9c138b10c9fc8d-refs/branch-heads/3396@{#771}
**操作系统 |** Windows
**JavaScript |** V8 6.7.288.46
**用户代理 |** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

**Comment by Tansc161** [comment]
https://github.com/cs12341795/yuribot/commit/4fa8d783a8120601442bac76284b9a3d5c465d6b 这个commit过后问题已解决，如没其他问题可关issue。
