### ISSUE TITLE
删除键不可用

### ISSUE THREAD

**Issue by Tansc161** [cs12341795/yuribot#2]
点了删除键后有发出了请求，但回应错误。

## 调试信息：
请求返回的数据
```HTTP
HTTP/1.1 302 Found
Server: Cowboy
Connection: keep-alive
Location: https://discordapp.com/api/oauth2/authorize?response_type=code&client_id=473523624079523840&redirect_uri=https://yuri-2018-04-21.herokuapp.com/discord/callback&scope=identify guilds&state=（验证码）
Content-Type: text/html; charset=utf-8
Content-Length: 473
Set-Cookie: （用户数据）
Date: （执行时间）
Via: 1.1 vegur

Redirecting to <a href="https://discordapp.com/api/oauth2/authorize?response_type=code&amp;client_id=473523624079523840&amp;redirect_uri=https://yuri-2018-04-21.herokuapp.com/discord/callback&amp;scope=identify guilds&amp;state=（验证码）">https://discordapp.com/api/oauth2/authorize?response_type=code&amp;client_id=473523624079523840&amp;redirect_uri=https://yuri-2018-04-21.herokuapp.com/discord/callback&amp;scope=identify guilds&amp;state=（验证码）</a>.
```

**Comment by ArmFire1911** [comment]
我這邊測試刪除測試兩個部分->未發出訊息的刪除&已發出訊息的刪除
未發出訊息的刪除為正常狀態
已發出訊息的刪除為"網頁上的刪除了但是Discord中的沒有"
猜測兩種可能
1.Bot本身問題
2.沒有給瑪利亞2 刪除訊息的權限

**Comment by supmiku39** [comment]
已更新

**Comment by Tansc161** [comment]
仍未解决，问题是对某些浏览器兼容不佳。

### 我按删除键时发送的数据是这样的：
```http
DELETE /tasks/158 HTTP/1.1
Host: yuri-2018-04-21.herokuapp.com
Connection: keep-alive
Origin: https://yuri-2018-04-21.herokuapp.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
DNT: 1
Accept: */*
Referer: https://yuri-2018-04-21.herokuapp.com/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7
```
可以看到并没有附上cookie，所以伺服器把请求给跳转到discord的oauth页面，然后浏览器把这个请求重丢给Discord，收到Method not Allowed错误，过后在console记录错误并终止动作。而因为前端会把页面刷新(`window.location.reload()`)，导致console消息被清除，然后还用户一个跟之前一模一样的页面。

## 我用的浏览器：
**Google Chrome |** 67.0.3396.87 (正式版本) （64 位） (cohort: Stable)
**修订版本 |** 878cd31214ac27a3996927cd5c9c138b10c9fc8d-refs/branch-heads/3396@{#771}
**操作系统 |** Windows
**JavaScript |** V8 6.7.288.46
**用户代理 |** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

**Comment by Tansc161** [comment]
https://github.com/cs12341795/yuribot/commit/4fa8d783a8120601442bac76284b9a3d5c465d6b 这个commit过后问题已解决，如没其他问题可关issue。
