### ISSUE TITLE
发布时间输入值过滤不严谨

### ISSUE THREAD

**Issue by Tansc161** [cs12341795/yuribot#3]
目前的情况是：
能输入任何在type: number范围里的值。

例：
0.0166666667分钟——1秒  （设置成功）
-525948分钟——去年          （设置成功）
超过Date可接受的值——∞  （设置成功）
不在number范涛的都会返回400 Bad Request错误。

**Comment by supmiku39** [comment]
已修正
若仍有問題可能是browser的版本問題，屆時請提供使用的browser的版本資訊以方便測試

**Comment by Tansc161** [comment]
已解决。
